### ISSUE TITLE
bb:InformationManagement meta:functionComponent bb:ModelingInformationSystems

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/ontology#500]
Problem with the edge [bb:InformationManagement meta:functionComponent bb:ModelingInformationSystems](http://www.snik.eu/ontology/bb/InformationManagement) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/InformationManagement&m=http://www.snik.eu/ontology/bb)):

Diese Kante muss weg. 

Als Ersatz brauchen wir ein entity type "HospitalInformationSystemModel", dass von http://www.snik.eu/ontology/bb/ModelingHospitalInformationSystems erzeugt wird und von http://www.snik.eu/ontology/bb/InformationManagement gelesen wird.

**Comment by KonradHoeffner** [comment]
- [ ] [bb:InformationManagement meta:functionComponent bb:ModelingInformationSystems](http://www.snik.eu/ontology/bb/InformationManagement) löschen
- [ ] bb:HospitalInformationSystemModel a meta:EntityType hinzufügen
- [ ] bb:ModelingHospitalInformationSystems ? bb:HospitalInformationSystemModel  hinzufügen ("creates" haben wir nicht)
- [ ] bb:InformationManagement uses bb:HospitalInformationSystemModel hinzufügen

**Comment by KonradHoeffner** [comment]
SNIK Graph funktionierte bei mir übrigens erst nach einem neuladen ohne Cache mit STRG + F5.

**Comment by KonradHoeffner** [comment]
![Screenshot from 2022-10-05 21-19-45](https://user-images.githubusercontent.com/839577/194144465-a2943125-6bd5-454a-9194-0e7f08b5a85f.png)

**Comment by AlfredWinter** [comment]
Ich starte https://www.snik.eu/graph/. Dann setze ich den Filter so, dass nur noch das BB angezeigt wird. Dann mach ich einen Star um Information management. Im Teilmodell 1 erscheint das ergebnis und die neuen Elemente sind geheileitet. Ich klicke auf Tight layout. Es passiert nichts. Ich klicke ins Fenster, die Heileits verschwinden. Dann klicke ich auf Tight Layout – und steht die Seite . 
 
AW
 
Von: Konrad Höffner ***@***.***> 
Gesendet: Donnerstag, 6. Oktober 2022 10:14
An: snikproject/ontology ***@***.***>
Cc: AlfredWinter ***@***.***>; Author ***@***.***>
Betreff: [Extern] Re: [snikproject/ontology] bb:InformationManagement meta:functionComponent bb:ModelingInformationSystems (Issue #500)
 
Können Sie es nochmal probieren und beschreiben, welche Schritte genau zu dem Aufhängen führen?

**Comment by KonradHoeffner** [comment]
Ja das scheint ein Problem mit tight layout gewesen zu sein.
Ich weiß leider nicht 100%ig woran das lag, habe aber eine Layoutfunktion vereinfacht und die Bibliotheken upgedated und jetzt tritt zumindest bei mir der Fehler nicht mehr auf, können Sie mal probieren ob es bei Ihnen jetzt auch geht?

**Comment by AlfredWinter** [comment]
super

**Comment by KonradHoeffner** [comment]
Zur Sicherheit ist die Anzahl der maximalen Iterationen und die maximale Simulationszeit vom tight layout jetzt auch drastisch heruntergesetzt, das benutzen wir ja sowieso eher für kleine Graphen.

**Comment by KonradHoeffner** [comment]
SNIK Graph ist nochmal kurz offline, ich muss da auf dem Server noch etwas umkonfigurieren.

**Comment by KonradHoeffner** [comment]
Hat etwas längert gedauert, jetzt geht es wieder.

**Comment by AlfredWinter** [comment]
In Chrome geht das Tight-Layout wieder; aber auch nur wenn man erstmal die ganzen Heileits wegklickt. 
Im Firefox geht’s trotz vieler Cache-Löschungen nicht. 
AW
 
Von: Konrad Höffner ***@***.***> 
Gesendet: Donnerstag, 6. Oktober 2022 15:19
An: snikproject/ontology ***@***.***>
Cc: AlfredWinter ***@***.***>; Author ***@***.***>
Betreff: [Extern] Re: [snikproject/ontology] bb:InformationManagement meta:functionComponent bb:ModelingInformationSystems (Issue #500)
 
Hat etwas länger gedauert, jetzt geht es wieder.

**Comment by KonradHoeffner** [comment]
Hm, ich untersuche das morgen mal weiter. Und wie ist es, wenn sie statt tight layout das recalculate layout nehmen?

**Comment by KonradHoeffner** [comment]
Für die Einfrierungsproblematik gibt es jetzt eine neue Issue: #501.

**Comment by AlfredWinter** [comment]
Nein, immer noch dasselbe. Habe auch STRG-F5 gedrückt. 
Von: Konrad Höffner ***@***.***> 
Gesendet: Donnerstag, 6. Oktober 2022 10:56
An: snikproject/ontology ***@***.***>
Cc: AlfredWinter ***@***.***>; Author ***@***.***>
Betreff: [Extern] Re: [snikproject/ontology] bb:InformationManagement meta:functionComponent bb:ModelingInformationSystems (Issue #500)
 
Ja das scheint ein Problem mit tight layout gewesen zu sein.
Ich weiß leider nicht 100%ig woran das lag, habe aber eine Layoutfunktion vereinfacht und die Bibliotheken upgedated und jetzt tritt zumindest bei mir der Fehler nicht mehr auf, können Sie mal probieren ob es bei Ihnen jetzt auch geht?
